// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAagPq6gGeqjvbcyFZpiRGnM9lsP7oOWrk',
    appId: '1:413154186328:web:4f374d5b8fcee64810662d',
    messagingSenderId: '413154186328',
    projectId: 'packup-90eda',
    authDomain: 'packup-90eda.firebaseapp.com',
    storageBucket: 'packup-90eda.firebasestorage.app',
    measurementId: 'G-E25CYQ4MFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvP0n8lZOZJ_7mDSLH4DLdrIxmqhJvi8',
    appId: '1:413154186328:android:081b9d1c50828b6410662d',
    messagingSenderId: '413154186328',
    projectId: 'packup-90eda',
    storageBucket: 'packup-90eda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Eij3t7Vtc4XGgFxV2HGvhI7_MVkcehY',
    appId: '1:413154186328:ios:8588a540e5194e8e10662d',
    messagingSenderId: '413154186328',
    projectId: 'packup-90eda',
    storageBucket: 'packup-90eda.firebasestorage.app',
    androidClientId: '413154186328-84nion7l8heo6c3t3gsqcokpvm0hs0hu.apps.googleusercontent.com',
    iosClientId: '413154186328-nano1ri0n83pud0nmpcmsuq5amf00ru7.apps.googleusercontent.com',
    iosBundleId: 'com.packup.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Eij3t7Vtc4XGgFxV2HGvhI7_MVkcehY',
    appId: '1:413154186328:ios:8588a540e5194e8e10662d',
    messagingSenderId: '413154186328',
    projectId: 'packup-90eda',
    storageBucket: 'packup-90eda.firebasestorage.app',
    androidClientId: '413154186328-84nion7l8heo6c3t3gsqcokpvm0hs0hu.apps.googleusercontent.com',
    iosClientId: '413154186328-nano1ri0n83pud0nmpcmsuq5amf00ru7.apps.googleusercontent.com',
    iosBundleId: 'com.packup.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAagPq6gGeqjvbcyFZpiRGnM9lsP7oOWrk',
    appId: '1:413154186328:web:2847da4dac55546410662d',
    messagingSenderId: '413154186328',
    projectId: 'packup-90eda',
    authDomain: 'packup-90eda.firebaseapp.com',
    storageBucket: 'packup-90eda.firebasestorage.app',
    measurementId: 'G-9TDEQN6TN3',
  );
}
